services:
  - type: web
    name: fastapi-backend
    runtime: python
    buildCommand: "python run.py"
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: your-db-name
          property: connectionString
